---
title: "COMPSCIX 415.2 Homework 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My Github repository for my assignments can be found at this URL: https://github.com/Cameronlane11/compscix-415-2-assignments.git

```{r}
library(mdsr)
library(tidyverse)
data("WorldCities")
```

Question 1: A data frame with 23,018 observations on the following 10 variables.

```{r}
glimpse(WorldCities)
```

```{r}
worldCities <- head(WorldCities, 200) # 200 rows
```

```{r}
country_col <- WorldCities$country
```

```{r}
unique(country_col)
```

```{r}
region_col <- WorldCities$region
```

```{r}
unique(region_col)
```


```{r}
country_col %>% unique()
```

```{r}
WorldCities %>% ggplot(aes(x = population)) +
geom_histogram()
```

```{r}
WorldCities %>% ggplot(aes(x = population)) +
geom_histogram() +
xlab('City Population')
```
```{r}
WorldCities %>% ggplot(aes(x = population)) +
geom_histogram() +
xlab('City Population') +
  ylab('Numb of People') +
  ggtitle('Camerons Sheet')
```

