---
title: "COMPSCIX 415.2 Homework 9/Final”"
author: "Cameron Snyder"
date: "April 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(broom)
library('rvest')
library(jsonlite)
library(leaflet)
library(htmltools)
library(shiny)
```


#Exercise 1 - Sampling Distributions, Functions and For Loops 
```{r}
# sample size
samp_size <- 100
# set the rate parameter
samp_rate <- 1/10000
# take sample
sample1 <- rexp(n = samp_size, rate = samp_rate)
samp_fun <- function(samp_size, samp_rate) {samp_avg <- mean(sample1)
  samp_std_dev <- sd(sample1)
  stats <- list(samp_avg = samp_avg, samp_std_dev = samp_std_dev)
  return(stats)
  }


```

#Step2
```{r}
# sample size
samp_size <- 50
# set the rate parameter
samp_rate <- 1/10000
# take sample
sample2 <- rexp(n = samp_size, rate = samp_rate)
samp_fun <- function(samp_size, samp_rate) {
  samp_avg <- mean(sample2)
  samp_std_dev <- sd(sample2)
  stats <- list(samp_avg = samp_avg, samp_std_dev = samp_std_dev)
  return(stats)
}

n <- 10
sample_mean2 <- rep(NA, n)
sample_sd2 <- rep(NA, n)

for(i in 1:n) {
  sample_mean2[i] <- i
}
```

#Excersize 2

```{r}
library(broom)
read_csv('train.csv')
```

#regression






# Excersize 3
```{r}
library(broom)
ab.testing <- 
  read_csv('ab_test_data.csv')
glimpse(ab.testing)
group.ab.testing <- ab.testing %>% 
  count(version, conversion == 1)
group.ab.testing
```
#proportions
```{r}
a.test <- 83/1917 * 100
a.test
```


Conversion for A is 4.3%

```{r}
b.test <- 200/1800 * 100
b.test
```

B is 11.1%

#abtests
```{r}
a.size <- 2000
b.size <-2000
a.test2 <- rbinom(n = 1, size = a.size, prob = a.test)
b.test2 <- rbinom(n = 1, size = b.size, prob = b.test)

```
P value = 
The P Value for A and B proportions is .14, meaning that the value is not signifcant

